config/routes.rb
Crumblr::Application.routes.draw do
  resources :reviews

  get "links/show"
  get "links/new"
  get "links/create"
  devise_for :users

  resources :pages
  resources :links
  root :to => "pages#index"

  

end

app/models/link.rb
class Link < ActiveRecord::Base
	belongs_to :user
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :user
	belongs_to :link
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :links
	has_many :review
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	#attr_accessible :email, :username
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController

	def index
		@links = Link.all
    @links = Link.order(:title).page(params[:page])
	end

  def show
  	@links = Link.find(params[:id])
  end

  def new
  	@links = Link.new
  end

  def create
  	@links = Link.new(link_params)
  	@links.save

  	flash.notice = "Link '#{@links.title} Created!"

  	redirect_to link_path(@links)
  end

  def link_params
  	params.require(:link).permit(:title, :url, :description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
	end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
    @review = Review.new
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render action: 'show', status: :created, location: @review }
      else
        format.html { render action: 'new' }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:user_id, :link_id, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
<div class="row-fluid">
  <nav class="span3">
  <h3>Links About Us</h3>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="#">Team</a></li>
    </ul>
  </nav>

<nav class="span3">
<h3>Our Sponsors</h3>
  <ul>
    <li><%= link_to "Sponsor 1",   '#' %></li>
    <li><%= link_to "Sponsor 2", '#' %></li>
    <li><a href="#">Sponsor 3</a></li>
  </ul>
</nav>

<nav class="span3">
<h3>Recommendations</h3>
  <ul>
    <li><%= link_to "Github",   'http://github.com/' %></li>
    <li><%= link_to "Linode", 'www.linode.com' %></li>
    <li><a href="www.thoughtbot.com">Thoughtbot</a></li>
  </ul>
</nav>

<nav class="span3">
<h3>Hosted On</h3>
  <img src="http://railsrumble.com.s3.amazonaws.com/sponsors/r13/sponsor-1380389614/sidebar/linode.png" height="90" width="90" />
</nav>
</div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Crumblr", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <%= link_to "Home", root_path, class: "btn btn-primary" %>
          <%= link_to "Help",    '#', class: "btn btn-primary" %>

          <% if current_user.present? %>
            <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "btn btn-primary" %>
          <% else %>
            <%= link_to 'Sign in', new_user_session_path, class: "btn btn-primary" %> 
            <%= link_to 'Register Now!', new_user_registration_path, class: "btn btn-primary" %>
          <% end %>

        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crumblr</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "/layouts/header" %>



<%= yield %>

<%= render "/layouts/footer" %>
</body>
</html>

app/views/links/_form.html.erb
<%= form_for(@links) do |f| %>
	<ul>
		<% @links.errors.full_messages.each do |error| %>
		  <li><%= error %></li>
		<% end %>
	</ul>


	<div class="field span4">
		<%= f.label :title %><br />
		<%= f.text_field :title%>
	</div>
	<div class="field span4">
		<%= f.label "Job link url" %><br />
		<%= f.text_field :url %>
	</div>
	<div class="description span4">
		<%= f.label :description %><br />
		<%= f.text_area :description %><br />
	</div>
	<div class="actions btn-primary">
		<%= f.submit %>
	</div>
<% end %>

app/views/links/create.html.erb
<h1>Links#create</h1>
<p>Find me in app/views/links/create.html.erb</p>

app/views/links/index.html.erb
<div class="page-header">
	<h1>All Job Links</h1>
</div>
<ul id="links">
	<% @links.each do |link| %>
		<li>
			
			<h3><%= link_to link.title, link_path(link), class: 'link_title' %>
			</h3>
			<br/>
			<div class="well">
			<p>Job Link<%= link_to link.url, link.url %></p><br/>
			<p>Description:<%= link.description %></p>
			<%= link_to "Review", new_review_path %>

			</div>
			
		</li>
	<% end %>
</ul>
<div class="pagination ">
	<%= paginate @links %>
</div>
<%= link_to "Add New Job Link", new_link_path(@links), class: "btn btn-primary" %>

app/views/links/new.html.erb
<h1>Add a new link</h1>

<%= render 'form' %>

app/views/links/show.html.erb
<div class="container">

      <div class="row">
        <div class="col-lg-8">
        
          <!-- the actual blog post: title/author/date/content -->
          <h1>
          	<h1><%= @links.title %></h1>
          </h1>
          <p class="lead">by Username
          </p>
          <hr>
          <p><span class="glyphicon glyphicon-time"></span> Posted on <%= @links.created_at %>
          </p>
          <hr>
          <img src="http://placehold.it/900x300" class="img-responsive">
          <hr>
          <p class="lead">
          	<b>Job Link URL</b>:<%= link_to @links.url, @links.url %>
         </p>

         <b>Job Description</b>: <%= @links.description %>


          <hr>

          <!-- the comment box -->
          <div class="well">
            <h4>Leave a Comment:</h4>
            <form role="form">
              <div class="form-group">
                <!-- <textarea class="form-control" rows="3"></textarea> -->
                <%= render "/reviews/form" %>
                
              </div>
            </form>
          </div>
          
          <hr>

          <!-- the comments -->
          <h3>Start Bootstrap <small>9:41 PM on August 24, 2013</small></h3>
          <p>This has to be the worst blog post I have ever read. It simply makes no sense. You start off by talking about space or something, then you randomly start babbling about cupcakes, and you end off with random fish names.</p>

          <h3>Start Bootstrap <small>9:47 PM on August 24, 2013</small></h3>
          <p>Don't listen to this guy, any blog with the categories 'dinosaurs, spaceships, fried foods, wild animals, alien abductions, business casual, robots, and fireworks' has true potential.</p>

        </div>
        
        <div class="col-lg-4">
          <div class="well">
            <h4>Blog Search</h4>
            <div class="input-group">
              <input type="text" class="form-control">
              <span class="input-group-btn">
                <button class="btn btn-default" type="button"><span class="glyphicon glyphicon-search"></span></button>
              </span>
            </div><!-- /input-group -->
          </div><!-- /well -->
          <div class="well">
            <h4>Popular Blog Categories</h4>
              <div class="row">
                <div class="col-lg-6">
                  <ul class="list-unstyled">
                    <li><a href="#dinosaurs">Dinosaurs</a></li>
                    <li><a href="#spaceships">Spaceships</a></li>
                    <li><a href="#fried-foods">Fried Foods</a></li>
                    <li><a href="#wild-animals">Wild Animals</a></li>
                  </ul>
                </div>
                <div class="col-lg-6">
                  <ul class="list-unstyled">
                    <li><a href="#alien-abductions">Alien Abductions</a></li>
                    <li><a href="#business-casual">Business Casual</a></li>
                    <li><a href="#robots">Robots</a></li>
                    <li><a href="#fireworks">Fireworks</a></li>
                  </ul>
                </div>
              </div>
          </div><!-- /well -->
          <div class="well">
            <h4>Side Widget Well</h4>
            <p>Bootstrap's default wells work great for side widgets! What is a widget anyways...?</p>
          </div><!-- /well -->
        </div>
      </div>
      
      <hr>
    </div>

app/views/pages/index.html.erb
<%= render "/layouts/header" %>

<div class="center hero-unit">
  <h1>Welcome to the Crumblr</h1>

  <h2>
    This application is a result of Rails Rumble.
  </h2>

  <%= link_to "Find Jobs Now!", "/links", class: "btn btn-large btn-primary" %>
</div>


<%= link_to "Add a link", new_link_path %>

app/views/reviews/_form.html.erb
<%= form_for Review.new do |f| %>
  <% if Review.new.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(Review.new.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% Review.new.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<h1>Listing reviews</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Link</th>
      <th>Body</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.user_id %></td>
        <td><%= review.link_id %></td>
        <td><%= review.body %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New review</h1>

<%= render 'form' %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @review.user_id %>
</p>

<p>
  <strong>Link:</strong>
  <%= @review.link_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @review.body %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>